uw-labs/substrate

kafka/integration_test.go
kafka/kafka.go
kafka/status.go

With Kafka, for both consumer and producers, introduce a new constructor
function, and establish a client connection to the broker(s)
immediately.  We use this client in the main consume & produce methods,
but also use the same client in the status call, to ensure we're
checking the actual client connection in use.

kafka : Connect early and reuse Client

---

sync_adapter_sink_test.go
sync_adapter_source_test.go

Use the same variable name for the receiver.

Use consistent naming

---

substrate.go
sync_adapter_source.go
sync_adapter_source_test.go

This changes the synchronous consumer callback function to additionally
take a context.Context so that handling can be interrupted.
Note that this represents an API change.

Pass context.Context to consumer callback

---

natsstreaming/nats_streaming.go

If an empty client id is provided for a sink, default a random one.

Default client id for sink

---

natsstreaming/nats_streaming.go

This fixes what I broke earlier, and renames to use Inflight rather than
InFlight.   Also, note https://github.com/uw-labs/substrate/issues/8

Fix earlier breakage

---

natsstreaming/nats_streaming.go

This exposes the AckWait option in the consumer options.  Previously
this was hard coded to 60s. Instead, we now use whatever the caller
specifies, or if they don't specify (i.e., specify a zero Duration) then
we use the nats streaming defaults.

Expose nats streaming consumer "ack wait"

---

natsstreaming/nats_streaming.go
testshared/testshared.go

This fixes two issues with ack handling.
Acks were not being cleared from the queue after acking, and there was a race condition where acks could be sent by the consumer before we have added them to the list of things to ack.

Fix to ack handling

---

kafka/kafka.go

Instead of hard coding the underlying values, use the sarama provided
constants.

Use sarama constants for offset values

---

kafka/doc.go
kafka/kafka_url.go
kafka/kafka_url_test.go
natsstreaming/doc.go
natsstreaming/nats_streaming_url.go
natsstreaming/nats_streaming_url_test.go
suburl/doc.go
suburl/sink.go
suburl/source.go

This implements a URL based connection approach, enabling switching
between different types of broken by configuration alone.  The various
drivers register themselves in much the same way as sql drivers used
with the standard library.
Some examples are below, see included documentation for more details.
```
source, err := suburl.NewSource("nats-streaming://localhost:4222/my-subject?cluster-id=foo&consumer-id=bar")
if err != nil {
// error handling
}
defer source.Close()
// use source here
```
```
Here is an example of obtaining a kafka sink.
sink, err := suburl.NewSink("kafka://localhost:9092/my-topic/?broker=localhost%3A9092&broker=localhost%3A9092")
if err != nil {
// error handling
}
defer sink.Close()
// use sink here
```

URL based connection

---

kafka/kafka_url_test.go

This updates a test to use the right url param.  Previously, we had
different values, they were changed to match the usual kafka
terminology, but this test was missed.

Fix kafka url parameter

---

internal/testshared/testshared.go
kafka/integration_test.go
natsstreaming/integration_test.go

This adds a new TestEnd method to the TestServer interface to allow each
test server a way to do cleanup etc after each test has run.  This is
not used anywhere (beyond empty implementation) just yet.

Add TestEnd method to TestServer

---

README.md
proximo/doc.go
proximo/integration_test.go
proximo/proximo_sink.go
proximo/proximo_source.go
proximo/proximo_url.go
proximo/proximo_url_test.go

This adds initial support for https://github.com/uw-labs/proximo as a
backend as both a source and a sink.
In order to better fit with substrates goals and design, we don't use
the default proximo client here.  This also leads to significantly
better throughput in my testing.
Also included is use of proximo via the substrate url based addressing.

Add initial proximo support

---

natsstreaming/nats_streaming.go
natsstreaming/nats_streaming_url.go
natsstreaming/nats_streaming_url_test.go

I also changed the default offset for NATS streaming to be the newest message to match the Kafka implementation. This change makes the two implementations consistent.
The code for parsing, the offset from the url can be abstracted, but I will leave this for another PR.

Add offset to nats streaming implementation.

---

sync_adapter_sink.go
sync_adapter_sink_test.go

Similarly as I did for the source I refactored the synchronous message sink using error group, what simplifies the logic. I've also slightly changed the behaviour of the publish method which now returns meaningful error to the client when sink is closed or when we fail to send the message.

Refactor synchronous message sink

---

instrumented/sink.go
instrumented/source.go

This is to avoid deadlock, when the context is cancelled after receiving the acknowledgement.

Pass acknowledgments in a select in the instrumented handler.

---

natsstreaming/status.go

There were previously two code paths that indicated in some way that
nats was not connected. One was that the connection was nil, and the
other that the connection was not nil, but IsConnected returned false.
The former returned an error, and the latter returned a non-working
status.
This is not useful to the caller who is expecting an error only if we
cannot establish the status.
Rework and simplify the code so that we always return a status object
(and no error) if we can establish that there is no connection.
Note that returning an error here should only happen if we fail to
establish whether or not things are working, which is actually not
something that ever happens for the nats check, given how the nats api
works.

Fix nats status check

---

internal/testshared/testshared.go
proximo/proximo_sink.go
proximo/proximo_source.go

This makes sure that the clients terminate as soon as one of the parts does. It also removes the need to control the flow using custom errors.
I also cleaned up the usage of the deprecated `grpc.Code` function.

Use run group instead of error group

---

proximo/integration_test.go
proximo/proximo_sink.go
proximo/proximo_source.go

Dependans on https://github.com/uw-labs/proximo/pull/70. This breaks the dependency on the client which we want to ultimately remove.

Use generated files from proximo package instead of proximoc.

---

proximo/doc.go
proximo/proximo.go
proximo/proximo_sink.go
proximo/proximo_source.go
proximo/proximo_url.go
proximo/proximo_url_test.go

Provides the ability for you to configure keep alive for
proximo clients that consume from a proximo server providing
keep alive functionality

feat: Keep Alive for proximo clients

---

sync_adapter_sink.go
sync_adapter_sink_test.go

With the old implementation we might miss the error from the backend in case publish is called before close.

Make sure that we propagate error from closing async sink.

---

instrumented/sink.go
instrumented/sink_test.go
instrumented/source.go
instrumented/source_test.go

The deadlock happens when trying to acknowledge a message when the backend has already terminated.

Fix deadlock in instrumented wrappers

---

proximo/doc.go
proximo/proximo.go
proximo/proximo_sink.go
proximo/proximo_source.go
proximo/proximo_url.go

We've published messages into kafka that exceed the 64MiB limit
here, so unfortunately this is leading to some services crashing.
Only making this available on the source config, as the sink case
doesn't _receive_ messages that are in any way bound to the size of
user supplied input.
Rather than adding another argument to dialProximo, I've wrapped
the arguments up in a struct. Hope that makes sense.
---
If this doesn't feel like it should be configurable we can also just set
it to `math.MaxInt32` - thoughts?

Configurable max receive message size

---

internal/unwrap/unwrap.go
internal/unwrap/unwrap_test.go
kafka/kafka.go
substrate.go
sync_adapter_sink.go

Currently when using synchronous adapter and Kafka we can't easily retrieve partition key from the substrate message, as the callback is called with an annotated one. With this change the user will receive the message they originally provided. We can potentially make the `AnnotatedMessage` interface private, but it will make implementing additional sink wrappers outside of the package easier.

Fix Kafka partition key callback, when using synchronous wrapper

---

kafka/integration_test.go
kafka/kafka.go

We were not handling rebalances correctly when there were multiple consumers in a group. This fixes that and adds a test that triggers 2 rebalances to ensure correct behaviour.

Restart Kafka consumer after rebalance.

---

kafka/kafka_url.go

Invalid assignment using `:=` to set a field on the config struct
Oops
Does make me wonder what `GolangCI` is actually doing - looks like it raised warnings caused by not being able to compile, but still reported all checks were successful

Fix bug causing compile error

---

kafka/kafka.go
kafka/kafka_url.go
kafka/kafka_url_test.go

The motivation for this is that the default in the old
sarama cluster library was 30s, wheres the new implementation
uses 10s. We stared seeing timeouts after the migration, so
we want to be able to increase the timeout as appropriate.

Make Kafka consumer session timeout configurable.

---

freezer/freezer_url.go
go.mod
go.sum

Update freezer to get zstd compression & change the freezer backend to
expose zstd in suburl.

Update freezer for zstd compression

---

freezer/freezer.go

The pattern for how we use slices here doesn't behave well for
allocations with the built-in approach for how and when to increase the
capacity.  Instead, detect ourselves when the capacity is not enough,
and use our own heuristics.

Reduce allocations

---

kafka/producer.go

Ensure we can never get blocked on sending a message to sarama when
sarama is no longer listening because we're shutting down.

Fix potential shutdown deadlock

---

kafka/consumer_group_handler.go
kafka/producer.go

Expand error messages to include information about whether it's a
producer or consumer message.  This is obviously useful now, having
tried to debug things in production.

Expand error message

---

kafka/consumer_group_handler.go

There are two paths that lead to processing acks, we only logged on one
of them.  Ensure we log on both

Add missing log message when debugging

---

internal/debug/debug.go

Profiling showed significant time spend calling the LogF method, just to
return when debug is disabled.  This is because it's not getting
inlined.
This moves everything except the enabled check to another method, making
LogF simple enough that the compiler can now inline it.

Tweak debug for better performance

---

freezer/freezer.go

Once we have seen an ack for a messages, we discard it from the slice of
messages to ack. However, we do this by slicing the slice to remove the
first element.  This doesn't actually free the message from memory at
that point, so to prevent excessive memory use, also set the data in the
message to nil.

Save memory in freezer source

---

internal/helper/sink_ack_ordering.go
internal/helper/sink_ack_ordering_test.go
internal/testshared/testshared.go
kafka/consumer.go
kafka/consumer_group_handler.go
kafka/integration_test.go
kafka/producer.go
natsstreaming/nats_streaming.go
proximo/proximo_sink.go
proximo/proximo_source.go
substrate.go

If we are exiting because the context is done, return ctx.Err() to be
consistent with some of the other backends.
Note that this behaviour used to be in place (at least partly) but was
changed with commit cf052fc0
Updates #126

Return ctx.Err() where appropriate.

---

go.mod
go.sum

Current version is marked not production-ready.
See: https://github.com/Shopify/sarama/releases/tag/v1.26.1

Upgrade sarama

---

freezer/freezer.go

This makes freezer messages discardable to enable lower memory use in
consumers.

Make freezer messages discardable

---

README.md

I've heard a few people mention that they didn't know about the existence of https://github.com/uw-labs/substrate-tools and have reinvented some existing, useful helpers.
Adding substrate-tools to the README as an additional resource means that we can more easily link the 2 for features that may not be suitable for substrate itself. That may also result in more pull requests landing at substrate-tools, instead of bloating the main package of substrate.
For the description of what substrate-tools is for, I wanted to keep it simple. If there was interest, we could include a summary of its relation to substrate as a destination for all the extra bells and whistles people may request.

Add reference to substrate-tools for useful extenstions to substrate

---

noop/noop_sink.go
noop/noop_sink_test.go
noop/noop_source.go
noop/noop_url.go

This is useful when we want to be able to easily disable consumption from one source.
We can use the noop reader and the service will behave as if no messages were coming in.
I have also updated the sink to return `ctx.Err()` instead of `nil` to make it match the
rest of the implementations.

Add noop source that blocks until the provided context is canceled.

---

sync_adapter_sink.go

This PR attempts to address an issue we've seen were a publisher might get stuck in a an endless loop of `sink was closed already` with the pod being reported as healthy.
I think the reason for this is that the `Status` implementation is missing a check on the `closed` channel. If an error happens while publishing for example because of the connection to kafka being lost, the channel will be closed and the producer will no longer be able to publish any messages because of this. But if the connection gets re-established the Status implementation will report `healthy`, as kafka is reachable and all, it's just our implementation that doesn't allow publishing messages because of the `closed` channel being already closed.

Check for closed channel on sync sink status implementation

---

kafka/integration_test.go
kafka/producer.go

I was investigating uneven message distribution across partitions in one of our services. We use a type that implements `KeyedMessage` but for this topic, we do not set a key by passing `nil`. I would have expected substrate to pass `nil` to Sarama and then for it fallback to using the random partitioner (https://github.com/Shopify/sarama/blob/v1.31.0/partitioner.go#L183-L185). However, we are passing the key directly to `sarama.ByteEncoder` which means we are passing an empty byte slice to Sarama/Kafka, thus getting the same hash each time (since `sarama.ProducerMessage.Key` is not null).
My Docker port command returns an IP6 address too, so in the test I've simply truncated that hence the change there too.

Set key only when non-nil
