uw-labs/substrate

- README.md
Added a godoc.org link to the readme.
> Add godoc link

- natsstreaming/integration_test.go
- natsstreaming/nats_streaming.go
Improve nats streaming configuration struct. See commits for details.
> Thinner nats abstraction

- natsstreaming/nats_streaming.go
This exposes the MaxInFlight option in the consumer options.  Previously
this was hard coded to 32.  Instead, we now use whatever the caller
specifics, or if they don't specify (i.e., specify 0) then we use the
nats streaming defaults.
> Expose nats streaming consumer "max in flight"

- natsstreaming/integration_test.go
This updates the version of nats streaming used in the integration test.
> Update nats streaming image

- internal/testshared/testshared.go
- kafka/kafka.go
- substrate.go
This introduces the ability to discard a message payload and implements it for kafka.
> Payload discarding kafka

- kafka/kafka.go
This changes Kafka source to use separate go-routines  one for receiving acknowledgements and another one for sending messages. This will avoid deadlock when the Kafka source is used with the synchronous adapter and more generally in cases when user wants to acknowledge a message before receiving another one.
> Change kafka source to use two use separate goroutines 

- sync_adapter_sink.go
Make sure the synchronous sink shuts down when the underlying message source does and clean up error handling when closing it.
> Synchronous sink refinements

- README.md
- freezer/doc.go
- freezer/freezer.go
- freezer/freezer_url.go
- freezer/freezer_url_test.go
- freezer/integration_test.go
This adds a backend for freezer
> Add freezer backend

- natsstreaming/integration_test.go
- natsstreaming/nats_streaming.go
> adds nats streaming ConnectionLostHandler

- proximo/proximo_source.go
- proximo/proximo_url.go
- proximo/proximo_url_test.go
- depends on https://github.com/uw-labs/proximo/pull/68
> support offset

- sync_adapter_sink.go
- sync_adapter_source.go
This simplifies the sink and fixes issue in the synchronous source that might hang in case calling `ConsumeMessages` terminates without an error.
> Use run-group in synchronous adapters.

- natsstreaming/nats_streaming.go
> fixes a race condition and a deadlock in nats sink

- natsstreaming/status.go
The old one no longer works, so use this.
> Fix package declaration

- sync_adapter_sink.go
I was hitting this a lot with partitioned Kafka backend, when publishing using the same sink in two different goroutines. My guess is that one broker was faster than another and so I ended up getting acknowledgements in seemingly the wrong order, even though the order fine as I'm performing concurrent writes. Making these changes solved my issue.
> Relax condition for acknowledgements order for synchronous sink adapter.

- freezer/freezer.go
This enables the caller to specify the max number of unflushed messages.
Previously it was hard coded to 1024, which has now become the default.
> Introduce MaxUnflushedMessages sink param

- instrumented/sink.go
- instrumented/source.go
Helps with the precision of prom queries.
> Initialise counter metrics

- noop/noop_sink.go
- noop/noop_sink_test.go
- noop/noop_url.go
- noop/noop_url_test.go
This sink is designed to only acknowledge messages, but not publish them (no operation)
Solves #85
> feat: Noop sink

- go.mod
- go.sum
- kafka/integration_test.go
- kafka/kafka.go
Remove use of `github.com/bsm/sarama-cluster`, replacing it with
equivalent support that now exists in sarama itself.
> Replace clustering code

- internal/debug/debug.go
- kafka/producer.go
- kafka/url.go
- kafka/url_test.go
- proximo/integration_test.go
- proximo/proximo_sink.go
- proximo/proximo_url.go
- proximo/proximo_url_test.go
This adds the first parts of debug logging functionality, to help give visibility into what is happening, which can be useful in various debugging scenarios.
> Debug logging

- internal/helper/sink_ack_ordering.go
- internal/helper/sink_ack_ordering_test.go
- kafka/producer.go
> Sink ack ordering

- go.mod
- go.sum
Upgrade freezer to include a memory leak fix.
> Upgrade freezer

- kafka/producer.go
See commit messages for details
> Fix more channel and goroutine issues in sink

- internal/helper/sink_ack_ordering.go
Since needAcks is buffered, we can end up getting an ack before we
realise we need it, leading to a slice index out of bounds.  We could
make needAcks unbuffered, but that will lead to more context switching,
so instead don't assume anything about the relative ordering of acks vs
acks needed.
> Fix slice index bug

- internal/debug/debug.go
- kafka/consumer.go
- kafka/consumer_group_handler.go
Expose debug information in the kafka consumer, when configured appropriately.
See commit messages for details.
> Kafka consumer debug
